/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as SettingsIndexRouteImport } from './routes/settings/index'
import { Route as CardsIndexRouteImport } from './routes/cards/index'
import { Route as AccountsIndexRouteImport } from './routes/accounts/index'
import { Route as TransactionsNewRouteImport } from './routes/transactions/new'
import { Route as CardsNewRouteImport } from './routes/cards/new'
import { Route as BillsNewRouteImport } from './routes/bills/new'
import { Route as AccountsNewRouteImport } from './routes/accounts/new'
import { Route as CardsCardIdIndexRouteImport } from './routes/cards/$cardId/index'
import { Route as AccountsAccountIdIndexRouteImport } from './routes/accounts/$accountId/index'
import { Route as CardsCardIdTransactionsNewRouteImport } from './routes/cards/$cardId/transactions/new'
import { Route as AccountsAccountIdTransactionsNewRouteImport } from './routes/accounts/$accountId/transactions/new'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const SettingsIndexRoute = SettingsIndexRouteImport.update({
  id: '/settings/',
  path: '/settings/',
  getParentRoute: () => rootRouteImport,
} as any)
const CardsIndexRoute = CardsIndexRouteImport.update({
  id: '/cards/',
  path: '/cards/',
  getParentRoute: () => rootRouteImport,
} as any)
const AccountsIndexRoute = AccountsIndexRouteImport.update({
  id: '/accounts/',
  path: '/accounts/',
  getParentRoute: () => rootRouteImport,
} as any)
const TransactionsNewRoute = TransactionsNewRouteImport.update({
  id: '/transactions/new',
  path: '/transactions/new',
  getParentRoute: () => rootRouteImport,
} as any)
const CardsNewRoute = CardsNewRouteImport.update({
  id: '/cards/new',
  path: '/cards/new',
  getParentRoute: () => rootRouteImport,
} as any)
const BillsNewRoute = BillsNewRouteImport.update({
  id: '/bills/new',
  path: '/bills/new',
  getParentRoute: () => rootRouteImport,
} as any)
const AccountsNewRoute = AccountsNewRouteImport.update({
  id: '/accounts/new',
  path: '/accounts/new',
  getParentRoute: () => rootRouteImport,
} as any)
const CardsCardIdIndexRoute = CardsCardIdIndexRouteImport.update({
  id: '/cards/$cardId/',
  path: '/cards/$cardId/',
  getParentRoute: () => rootRouteImport,
} as any)
const AccountsAccountIdIndexRoute = AccountsAccountIdIndexRouteImport.update({
  id: '/accounts/$accountId/',
  path: '/accounts/$accountId/',
  getParentRoute: () => rootRouteImport,
} as any)
const CardsCardIdTransactionsNewRoute =
  CardsCardIdTransactionsNewRouteImport.update({
    id: '/cards/$cardId/transactions/new',
    path: '/cards/$cardId/transactions/new',
    getParentRoute: () => rootRouteImport,
  } as any)
const AccountsAccountIdTransactionsNewRoute =
  AccountsAccountIdTransactionsNewRouteImport.update({
    id: '/accounts/$accountId/transactions/new',
    path: '/accounts/$accountId/transactions/new',
    getParentRoute: () => rootRouteImport,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/accounts/new': typeof AccountsNewRoute
  '/bills/new': typeof BillsNewRoute
  '/cards/new': typeof CardsNewRoute
  '/transactions/new': typeof TransactionsNewRoute
  '/accounts/': typeof AccountsIndexRoute
  '/cards/': typeof CardsIndexRoute
  '/settings/': typeof SettingsIndexRoute
  '/accounts/$accountId/': typeof AccountsAccountIdIndexRoute
  '/cards/$cardId/': typeof CardsCardIdIndexRoute
  '/accounts/$accountId/transactions/new': typeof AccountsAccountIdTransactionsNewRoute
  '/cards/$cardId/transactions/new': typeof CardsCardIdTransactionsNewRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/accounts/new': typeof AccountsNewRoute
  '/bills/new': typeof BillsNewRoute
  '/cards/new': typeof CardsNewRoute
  '/transactions/new': typeof TransactionsNewRoute
  '/accounts': typeof AccountsIndexRoute
  '/cards': typeof CardsIndexRoute
  '/settings': typeof SettingsIndexRoute
  '/accounts/$accountId': typeof AccountsAccountIdIndexRoute
  '/cards/$cardId': typeof CardsCardIdIndexRoute
  '/accounts/$accountId/transactions/new': typeof AccountsAccountIdTransactionsNewRoute
  '/cards/$cardId/transactions/new': typeof CardsCardIdTransactionsNewRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/accounts/new': typeof AccountsNewRoute
  '/bills/new': typeof BillsNewRoute
  '/cards/new': typeof CardsNewRoute
  '/transactions/new': typeof TransactionsNewRoute
  '/accounts/': typeof AccountsIndexRoute
  '/cards/': typeof CardsIndexRoute
  '/settings/': typeof SettingsIndexRoute
  '/accounts/$accountId/': typeof AccountsAccountIdIndexRoute
  '/cards/$cardId/': typeof CardsCardIdIndexRoute
  '/accounts/$accountId/transactions/new': typeof AccountsAccountIdTransactionsNewRoute
  '/cards/$cardId/transactions/new': typeof CardsCardIdTransactionsNewRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/accounts/new'
    | '/bills/new'
    | '/cards/new'
    | '/transactions/new'
    | '/accounts/'
    | '/cards/'
    | '/settings/'
    | '/accounts/$accountId/'
    | '/cards/$cardId/'
    | '/accounts/$accountId/transactions/new'
    | '/cards/$cardId/transactions/new'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/accounts/new'
    | '/bills/new'
    | '/cards/new'
    | '/transactions/new'
    | '/accounts'
    | '/cards'
    | '/settings'
    | '/accounts/$accountId'
    | '/cards/$cardId'
    | '/accounts/$accountId/transactions/new'
    | '/cards/$cardId/transactions/new'
  id:
    | '__root__'
    | '/'
    | '/accounts/new'
    | '/bills/new'
    | '/cards/new'
    | '/transactions/new'
    | '/accounts/'
    | '/cards/'
    | '/settings/'
    | '/accounts/$accountId/'
    | '/cards/$cardId/'
    | '/accounts/$accountId/transactions/new'
    | '/cards/$cardId/transactions/new'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AccountsNewRoute: typeof AccountsNewRoute
  BillsNewRoute: typeof BillsNewRoute
  CardsNewRoute: typeof CardsNewRoute
  TransactionsNewRoute: typeof TransactionsNewRoute
  AccountsIndexRoute: typeof AccountsIndexRoute
  CardsIndexRoute: typeof CardsIndexRoute
  SettingsIndexRoute: typeof SettingsIndexRoute
  AccountsAccountIdIndexRoute: typeof AccountsAccountIdIndexRoute
  CardsCardIdIndexRoute: typeof CardsCardIdIndexRoute
  AccountsAccountIdTransactionsNewRoute: typeof AccountsAccountIdTransactionsNewRoute
  CardsCardIdTransactionsNewRoute: typeof CardsCardIdTransactionsNewRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/settings/': {
      id: '/settings/'
      path: '/settings'
      fullPath: '/settings/'
      preLoaderRoute: typeof SettingsIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/cards/': {
      id: '/cards/'
      path: '/cards'
      fullPath: '/cards/'
      preLoaderRoute: typeof CardsIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/accounts/': {
      id: '/accounts/'
      path: '/accounts'
      fullPath: '/accounts/'
      preLoaderRoute: typeof AccountsIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/transactions/new': {
      id: '/transactions/new'
      path: '/transactions/new'
      fullPath: '/transactions/new'
      preLoaderRoute: typeof TransactionsNewRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/cards/new': {
      id: '/cards/new'
      path: '/cards/new'
      fullPath: '/cards/new'
      preLoaderRoute: typeof CardsNewRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/bills/new': {
      id: '/bills/new'
      path: '/bills/new'
      fullPath: '/bills/new'
      preLoaderRoute: typeof BillsNewRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/accounts/new': {
      id: '/accounts/new'
      path: '/accounts/new'
      fullPath: '/accounts/new'
      preLoaderRoute: typeof AccountsNewRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/cards/$cardId/': {
      id: '/cards/$cardId/'
      path: '/cards/$cardId'
      fullPath: '/cards/$cardId/'
      preLoaderRoute: typeof CardsCardIdIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/accounts/$accountId/': {
      id: '/accounts/$accountId/'
      path: '/accounts/$accountId'
      fullPath: '/accounts/$accountId/'
      preLoaderRoute: typeof AccountsAccountIdIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/cards/$cardId/transactions/new': {
      id: '/cards/$cardId/transactions/new'
      path: '/cards/$cardId/transactions/new'
      fullPath: '/cards/$cardId/transactions/new'
      preLoaderRoute: typeof CardsCardIdTransactionsNewRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/accounts/$accountId/transactions/new': {
      id: '/accounts/$accountId/transactions/new'
      path: '/accounts/$accountId/transactions/new'
      fullPath: '/accounts/$accountId/transactions/new'
      preLoaderRoute: typeof AccountsAccountIdTransactionsNewRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AccountsNewRoute: AccountsNewRoute,
  BillsNewRoute: BillsNewRoute,
  CardsNewRoute: CardsNewRoute,
  TransactionsNewRoute: TransactionsNewRoute,
  AccountsIndexRoute: AccountsIndexRoute,
  CardsIndexRoute: CardsIndexRoute,
  SettingsIndexRoute: SettingsIndexRoute,
  AccountsAccountIdIndexRoute: AccountsAccountIdIndexRoute,
  CardsCardIdIndexRoute: CardsCardIdIndexRoute,
  AccountsAccountIdTransactionsNewRoute: AccountsAccountIdTransactionsNewRoute,
  CardsCardIdTransactionsNewRoute: CardsCardIdTransactionsNewRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
